---
name: "label-sync"

on:
  push:
    branches:
      - '**'

permissions:
  issues: write

jobs:
  labelsync:
    uses: schubergphilis/mcaf-github-workflows/.github/workflows/label-synchronization.yaml@feature/yamllint_workflow
